# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 1.imports.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from 0 import nested_type_pb2 as 0_dot_nested__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x31.imports.proto\x1a\x13\x30.nested_type.proto\"-\n\rMessageImport\x12\x1c\n\x05three\x18\x02 \x01(\x0b\x32\r.MessageThreeb\x06proto3')



_MESSAGEIMPORT = DESCRIPTOR.message_types_by_name['MessageImport']
MessageImport = _reflection.GeneratedProtocolMessageType('MessageImport', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEIMPORT,
  '__module__' : '1.imports_pb2'
  # @@protoc_insertion_point(class_scope:MessageImport)
  })
_sym_db.RegisterMessage(MessageImport)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEIMPORT._serialized_start=40
  _MESSAGEIMPORT._serialized_end=85
# @@protoc_insertion_point(module_scope)
