# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: 2b.use-package.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from 2a import package_pb2 as 2a_dot_package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x32\x62.use-package.proto\x1a\x10\x32\x61.package.proto\">\n\x11MessageUsePackage\x12)\n\x05hello\x18\x01 \x01(\x0b\x32\x1a.my.package.MessagePackageb\x06proto3')



_MESSAGEUSEPACKAGE = DESCRIPTOR.message_types_by_name['MessageUsePackage']
MessageUsePackage = _reflection.GeneratedProtocolMessageType('MessageUsePackage', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEUSEPACKAGE,
  '__module__' : '2b.use_package_pb2'
  # @@protoc_insertion_point(class_scope:MessageUsePackage)
  })
_sym_db.RegisterMessage(MessageUsePackage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEUSEPACKAGE._serialized_start=42
  _MESSAGEUSEPACKAGE._serialized_end=104
# @@protoc_insertion_point(module_scope)
