# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bottom_up_nested.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62ottom_up_nested.proto\"\xb4\x02\n\x08\x42uilding\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\r\x12 \n\x06street\x18\x03 \x01(\x0b\x32\x10.Building.Street\x1a\xe7\x01\n\x06Street\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x04\x63ity\x18\x02 \x01(\x0b\x32\x15.Building.Street.City\x1a\xa9\x01\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08zip_code\x18\x02 \x01(\t\x12\x33\n\x0c\x63ountry_name\x18\x03 \x01(\x0e\x32\x1d.Building.Street.City.Country\"L\n\x07\x43ountry\x12\x17\n\x13\x43OUNTRY_UNSPECIFIED\x10\x00\x12\x12\n\x0eUNITIED_STATES\x10\x01\x12\t\n\x05\x43HINA\x10\x02\x12\t\n\x05JAPAN\x10\x03\"m\n\x07\x41\x64\x64ress\x12#\n\x04\x63ity\x18\x01 \x01(\x0b\x32\x15.Building.Street.City\x12 \n\x06street\x18\x02 \x01(\x0b\x32\x10.Building.Street\x12\x1b\n\x08\x62uilding\x18\x03 \x01(\x0b\x32\t.Buildingb\x06proto3')



_BUILDING = DESCRIPTOR.message_types_by_name['Building']
_BUILDING_STREET = _BUILDING.nested_types_by_name['Street']
_BUILDING_STREET_CITY = _BUILDING_STREET.nested_types_by_name['City']
_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
_BUILDING_STREET_CITY_COUNTRY = _BUILDING_STREET_CITY.enum_types_by_name['Country']
Building = _reflection.GeneratedProtocolMessageType('Building', (_message.Message,), {

  'Street' : _reflection.GeneratedProtocolMessageType('Street', (_message.Message,), {

    'City' : _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
      'DESCRIPTOR' : _BUILDING_STREET_CITY,
      '__module__' : 'bottom_up_nested_pb2'
      # @@protoc_insertion_point(class_scope:Building.Street.City)
      })
    ,
    'DESCRIPTOR' : _BUILDING_STREET,
    '__module__' : 'bottom_up_nested_pb2'
    # @@protoc_insertion_point(class_scope:Building.Street)
    })
  ,
  'DESCRIPTOR' : _BUILDING,
  '__module__' : 'bottom_up_nested_pb2'
  # @@protoc_insertion_point(class_scope:Building)
  })
_sym_db.RegisterMessage(Building)
_sym_db.RegisterMessage(Building.Street)
_sym_db.RegisterMessage(Building.Street.City)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'bottom_up_nested_pb2'
  # @@protoc_insertion_point(class_scope:Address)
  })
_sym_db.RegisterMessage(Address)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUILDING._serialized_start=27
  _BUILDING._serialized_end=335
  _BUILDING_STREET._serialized_start=104
  _BUILDING_STREET._serialized_end=335
  _BUILDING_STREET_CITY._serialized_start=166
  _BUILDING_STREET_CITY._serialized_end=335
  _BUILDING_STREET_CITY_COUNTRY._serialized_start=259
  _BUILDING_STREET_CITY_COUNTRY._serialized_end=335
  _ADDRESS._serialized_start=337
  _ADDRESS._serialized_end=446
# @@protoc_insertion_point(module_scope)
