// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

public final class AddressOuterClass {
  private AddressOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.City city = 1;</code>
     * @return Whether the city field is set.
     */
    boolean hasCity();
    /**
     * <code>.City city = 1;</code>
     * @return The city.
     */
    CityOuterClass.City getCity();
    /**
     * <code>.City city = 1;</code>
     */
    CityOuterClass.CityOrBuilder getCityOrBuilder();

    /**
     * <code>.my.street.Street street = 2;</code>
     * @return Whether the street field is set.
     */
    boolean hasStreet();
    /**
     * <code>.my.street.Street street = 2;</code>
     * @return The street.
     */
    my.street.StreetOuterClass.Street getStreet();
    /**
     * <code>.my.street.Street street = 2;</code>
     */
    my.street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder();

    /**
     * <code>.Building building = 3;</code>
     * @return Whether the building field is set.
     */
    boolean hasBuilding();
    /**
     * <code>.Building building = 3;</code>
     * @return The building.
     */
    BuildingOuterClass.Building getBuilding();
    /**
     * <code>.Building building = 3;</code>
     */
    BuildingOuterClass.BuildingOrBuilder getBuildingOrBuilder();
  }
  /**
   * Protobuf type {@code Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              CityOuterClass.City.Builder subBuilder = null;
              if (city_ != null) {
                subBuilder = city_.toBuilder();
              }
              city_ = input.readMessage(CityOuterClass.City.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(city_);
                city_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              my.street.StreetOuterClass.Street.Builder subBuilder = null;
              if (street_ != null) {
                subBuilder = street_.toBuilder();
              }
              street_ = input.readMessage(my.street.StreetOuterClass.Street.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(street_);
                street_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              BuildingOuterClass.Building.Builder subBuilder = null;
              if (building_ != null) {
                subBuilder = building_.toBuilder();
              }
              building_ = input.readMessage(BuildingOuterClass.Building.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(building_);
                building_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AddressOuterClass.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AddressOuterClass.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressOuterClass.Address.class, AddressOuterClass.Address.Builder.class);
    }

    public static final int CITY_FIELD_NUMBER = 1;
    private CityOuterClass.City city_;
    /**
     * <code>.City city = 1;</code>
     * @return Whether the city field is set.
     */
    @java.lang.Override
    public boolean hasCity() {
      return city_ != null;
    }
    /**
     * <code>.City city = 1;</code>
     * @return The city.
     */
    @java.lang.Override
    public CityOuterClass.City getCity() {
      return city_ == null ? CityOuterClass.City.getDefaultInstance() : city_;
    }
    /**
     * <code>.City city = 1;</code>
     */
    @java.lang.Override
    public CityOuterClass.CityOrBuilder getCityOrBuilder() {
      return getCity();
    }

    public static final int STREET_FIELD_NUMBER = 2;
    private my.street.StreetOuterClass.Street street_;
    /**
     * <code>.my.street.Street street = 2;</code>
     * @return Whether the street field is set.
     */
    @java.lang.Override
    public boolean hasStreet() {
      return street_ != null;
    }
    /**
     * <code>.my.street.Street street = 2;</code>
     * @return The street.
     */
    @java.lang.Override
    public my.street.StreetOuterClass.Street getStreet() {
      return street_ == null ? my.street.StreetOuterClass.Street.getDefaultInstance() : street_;
    }
    /**
     * <code>.my.street.Street street = 2;</code>
     */
    @java.lang.Override
    public my.street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder() {
      return getStreet();
    }

    public static final int BUILDING_FIELD_NUMBER = 3;
    private BuildingOuterClass.Building building_;
    /**
     * <code>.Building building = 3;</code>
     * @return Whether the building field is set.
     */
    @java.lang.Override
    public boolean hasBuilding() {
      return building_ != null;
    }
    /**
     * <code>.Building building = 3;</code>
     * @return The building.
     */
    @java.lang.Override
    public BuildingOuterClass.Building getBuilding() {
      return building_ == null ? BuildingOuterClass.Building.getDefaultInstance() : building_;
    }
    /**
     * <code>.Building building = 3;</code>
     */
    @java.lang.Override
    public BuildingOuterClass.BuildingOrBuilder getBuildingOrBuilder() {
      return getBuilding();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (city_ != null) {
        output.writeMessage(1, getCity());
      }
      if (street_ != null) {
        output.writeMessage(2, getStreet());
      }
      if (building_ != null) {
        output.writeMessage(3, getBuilding());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (city_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCity());
      }
      if (street_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStreet());
      }
      if (building_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBuilding());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AddressOuterClass.Address)) {
        return super.equals(obj);
      }
      AddressOuterClass.Address other = (AddressOuterClass.Address) obj;

      if (hasCity() != other.hasCity()) return false;
      if (hasCity()) {
        if (!getCity()
            .equals(other.getCity())) return false;
      }
      if (hasStreet() != other.hasStreet()) return false;
      if (hasStreet()) {
        if (!getStreet()
            .equals(other.getStreet())) return false;
      }
      if (hasBuilding() != other.hasBuilding()) return false;
      if (hasBuilding()) {
        if (!getBuilding()
            .equals(other.getBuilding())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCity()) {
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
      }
      if (hasStreet()) {
        hash = (37 * hash) + STREET_FIELD_NUMBER;
        hash = (53 * hash) + getStreet().hashCode();
      }
      if (hasBuilding()) {
        hash = (37 * hash) + BUILDING_FIELD_NUMBER;
        hash = (53 * hash) + getBuilding().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressOuterClass.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AddressOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AddressOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AddressOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        AddressOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AddressOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AddressOuterClass.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AddressOuterClass.Address.class, AddressOuterClass.Address.Builder.class);
      }

      // Construct using AddressOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (cityBuilder_ == null) {
          city_ = null;
        } else {
          city_ = null;
          cityBuilder_ = null;
        }
        if (streetBuilder_ == null) {
          street_ = null;
        } else {
          street_ = null;
          streetBuilder_ = null;
        }
        if (buildingBuilder_ == null) {
          building_ = null;
        } else {
          building_ = null;
          buildingBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AddressOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public AddressOuterClass.Address getDefaultInstanceForType() {
        return AddressOuterClass.Address.getDefaultInstance();
      }

      @java.lang.Override
      public AddressOuterClass.Address build() {
        AddressOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AddressOuterClass.Address buildPartial() {
        AddressOuterClass.Address result = new AddressOuterClass.Address(this);
        if (cityBuilder_ == null) {
          result.city_ = city_;
        } else {
          result.city_ = cityBuilder_.build();
        }
        if (streetBuilder_ == null) {
          result.street_ = street_;
        } else {
          result.street_ = streetBuilder_.build();
        }
        if (buildingBuilder_ == null) {
          result.building_ = building_;
        } else {
          result.building_ = buildingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AddressOuterClass.Address) {
          return mergeFrom((AddressOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AddressOuterClass.Address other) {
        if (other == AddressOuterClass.Address.getDefaultInstance()) return this;
        if (other.hasCity()) {
          mergeCity(other.getCity());
        }
        if (other.hasStreet()) {
          mergeStreet(other.getStreet());
        }
        if (other.hasBuilding()) {
          mergeBuilding(other.getBuilding());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AddressOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AddressOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private CityOuterClass.City city_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CityOuterClass.City, CityOuterClass.City.Builder, CityOuterClass.CityOrBuilder> cityBuilder_;
      /**
       * <code>.City city = 1;</code>
       * @return Whether the city field is set.
       */
      public boolean hasCity() {
        return cityBuilder_ != null || city_ != null;
      }
      /**
       * <code>.City city = 1;</code>
       * @return The city.
       */
      public CityOuterClass.City getCity() {
        if (cityBuilder_ == null) {
          return city_ == null ? CityOuterClass.City.getDefaultInstance() : city_;
        } else {
          return cityBuilder_.getMessage();
        }
      }
      /**
       * <code>.City city = 1;</code>
       */
      public Builder setCity(CityOuterClass.City value) {
        if (cityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          city_ = value;
          onChanged();
        } else {
          cityBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.City city = 1;</code>
       */
      public Builder setCity(
          CityOuterClass.City.Builder builderForValue) {
        if (cityBuilder_ == null) {
          city_ = builderForValue.build();
          onChanged();
        } else {
          cityBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.City city = 1;</code>
       */
      public Builder mergeCity(CityOuterClass.City value) {
        if (cityBuilder_ == null) {
          if (city_ != null) {
            city_ =
              CityOuterClass.City.newBuilder(city_).mergeFrom(value).buildPartial();
          } else {
            city_ = value;
          }
          onChanged();
        } else {
          cityBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.City city = 1;</code>
       */
      public Builder clearCity() {
        if (cityBuilder_ == null) {
          city_ = null;
          onChanged();
        } else {
          city_ = null;
          cityBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.City city = 1;</code>
       */
      public CityOuterClass.City.Builder getCityBuilder() {
        
        onChanged();
        return getCityFieldBuilder().getBuilder();
      }
      /**
       * <code>.City city = 1;</code>
       */
      public CityOuterClass.CityOrBuilder getCityOrBuilder() {
        if (cityBuilder_ != null) {
          return cityBuilder_.getMessageOrBuilder();
        } else {
          return city_ == null ?
              CityOuterClass.City.getDefaultInstance() : city_;
        }
      }
      /**
       * <code>.City city = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CityOuterClass.City, CityOuterClass.City.Builder, CityOuterClass.CityOrBuilder> 
          getCityFieldBuilder() {
        if (cityBuilder_ == null) {
          cityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CityOuterClass.City, CityOuterClass.City.Builder, CityOuterClass.CityOrBuilder>(
                  getCity(),
                  getParentForChildren(),
                  isClean());
          city_ = null;
        }
        return cityBuilder_;
      }

      private my.street.StreetOuterClass.Street street_;
      private com.google.protobuf.SingleFieldBuilderV3<
          my.street.StreetOuterClass.Street, my.street.StreetOuterClass.Street.Builder, my.street.StreetOuterClass.StreetOrBuilder> streetBuilder_;
      /**
       * <code>.my.street.Street street = 2;</code>
       * @return Whether the street field is set.
       */
      public boolean hasStreet() {
        return streetBuilder_ != null || street_ != null;
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       * @return The street.
       */
      public my.street.StreetOuterClass.Street getStreet() {
        if (streetBuilder_ == null) {
          return street_ == null ? my.street.StreetOuterClass.Street.getDefaultInstance() : street_;
        } else {
          return streetBuilder_.getMessage();
        }
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public Builder setStreet(my.street.StreetOuterClass.Street value) {
        if (streetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          street_ = value;
          onChanged();
        } else {
          streetBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public Builder setStreet(
          my.street.StreetOuterClass.Street.Builder builderForValue) {
        if (streetBuilder_ == null) {
          street_ = builderForValue.build();
          onChanged();
        } else {
          streetBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public Builder mergeStreet(my.street.StreetOuterClass.Street value) {
        if (streetBuilder_ == null) {
          if (street_ != null) {
            street_ =
              my.street.StreetOuterClass.Street.newBuilder(street_).mergeFrom(value).buildPartial();
          } else {
            street_ = value;
          }
          onChanged();
        } else {
          streetBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public Builder clearStreet() {
        if (streetBuilder_ == null) {
          street_ = null;
          onChanged();
        } else {
          street_ = null;
          streetBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public my.street.StreetOuterClass.Street.Builder getStreetBuilder() {
        
        onChanged();
        return getStreetFieldBuilder().getBuilder();
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      public my.street.StreetOuterClass.StreetOrBuilder getStreetOrBuilder() {
        if (streetBuilder_ != null) {
          return streetBuilder_.getMessageOrBuilder();
        } else {
          return street_ == null ?
              my.street.StreetOuterClass.Street.getDefaultInstance() : street_;
        }
      }
      /**
       * <code>.my.street.Street street = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          my.street.StreetOuterClass.Street, my.street.StreetOuterClass.Street.Builder, my.street.StreetOuterClass.StreetOrBuilder> 
          getStreetFieldBuilder() {
        if (streetBuilder_ == null) {
          streetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              my.street.StreetOuterClass.Street, my.street.StreetOuterClass.Street.Builder, my.street.StreetOuterClass.StreetOrBuilder>(
                  getStreet(),
                  getParentForChildren(),
                  isClean());
          street_ = null;
        }
        return streetBuilder_;
      }

      private BuildingOuterClass.Building building_;
      private com.google.protobuf.SingleFieldBuilderV3<
          BuildingOuterClass.Building, BuildingOuterClass.Building.Builder, BuildingOuterClass.BuildingOrBuilder> buildingBuilder_;
      /**
       * <code>.Building building = 3;</code>
       * @return Whether the building field is set.
       */
      public boolean hasBuilding() {
        return buildingBuilder_ != null || building_ != null;
      }
      /**
       * <code>.Building building = 3;</code>
       * @return The building.
       */
      public BuildingOuterClass.Building getBuilding() {
        if (buildingBuilder_ == null) {
          return building_ == null ? BuildingOuterClass.Building.getDefaultInstance() : building_;
        } else {
          return buildingBuilder_.getMessage();
        }
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public Builder setBuilding(BuildingOuterClass.Building value) {
        if (buildingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          building_ = value;
          onChanged();
        } else {
          buildingBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public Builder setBuilding(
          BuildingOuterClass.Building.Builder builderForValue) {
        if (buildingBuilder_ == null) {
          building_ = builderForValue.build();
          onChanged();
        } else {
          buildingBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public Builder mergeBuilding(BuildingOuterClass.Building value) {
        if (buildingBuilder_ == null) {
          if (building_ != null) {
            building_ =
              BuildingOuterClass.Building.newBuilder(building_).mergeFrom(value).buildPartial();
          } else {
            building_ = value;
          }
          onChanged();
        } else {
          buildingBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public Builder clearBuilding() {
        if (buildingBuilder_ == null) {
          building_ = null;
          onChanged();
        } else {
          building_ = null;
          buildingBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public BuildingOuterClass.Building.Builder getBuildingBuilder() {
        
        onChanged();
        return getBuildingFieldBuilder().getBuilder();
      }
      /**
       * <code>.Building building = 3;</code>
       */
      public BuildingOuterClass.BuildingOrBuilder getBuildingOrBuilder() {
        if (buildingBuilder_ != null) {
          return buildingBuilder_.getMessageOrBuilder();
        } else {
          return building_ == null ?
              BuildingOuterClass.Building.getDefaultInstance() : building_;
        }
      }
      /**
       * <code>.Building building = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          BuildingOuterClass.Building, BuildingOuterClass.Building.Builder, BuildingOuterClass.BuildingOrBuilder> 
          getBuildingFieldBuilder() {
        if (buildingBuilder_ == null) {
          buildingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              BuildingOuterClass.Building, BuildingOuterClass.Building.Builder, BuildingOuterClass.BuildingOrBuilder>(
                  getBuilding(),
                  getParentForChildren(),
                  isClean());
          building_ = null;
        }
        return buildingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final AddressOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AddressOuterClass.Address();
    }

    public static AddressOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AddressOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raddress.proto\032\ncity.proto\032\014street.prot" +
      "o\032\016building.proto\"^\n\007Address\022\023\n\004city\030\001 \001" +
      "(\0132\005.City\022!\n\006street\030\002 \001(\0132\021.my.street.St" +
      "reet\022\033\n\010building\030\003 \001(\0132\t.Buildingb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          CityOuterClass.getDescriptor(),
          my.street.StreetOuterClass.getDescriptor(),
          BuildingOuterClass.getDescriptor(),
        });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "City", "Street", "Building", });
    CityOuterClass.getDescriptor();
    my.street.StreetOuterClass.getDescriptor();
    BuildingOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
