// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 1.imports.proto

public final class 1Imports {
  private 1Imports() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageImportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageImport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MessageThree three = 2;</code>
     * @return Whether the three field is set.
     */
    boolean hasThree();
    /**
     * <code>.MessageThree three = 2;</code>
     * @return The three.
     */
    0NestedType.MessageThree getThree();
    /**
     * <code>.MessageThree three = 2;</code>
     */
    0NestedType.MessageThreeOrBuilder getThreeOrBuilder();
  }
  /**
   * Protobuf type {@code MessageImport}
   */
  public static final class MessageImport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageImport)
      MessageImportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageImport.newBuilder() to construct.
    private MessageImport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageImport() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageImport();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageImport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              0NestedType.MessageThree.Builder subBuilder = null;
              if (three_ != null) {
                subBuilder = three_.toBuilder();
              }
              three_ = input.readMessage(0NestedType.MessageThree.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(three_);
                three_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 1Imports.internal_static_MessageImport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 1Imports.internal_static_MessageImport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              1Imports.MessageImport.class, 1Imports.MessageImport.Builder.class);
    }

    public static final int THREE_FIELD_NUMBER = 2;
    private 0NestedType.MessageThree three_;
    /**
     * <code>.MessageThree three = 2;</code>
     * @return Whether the three field is set.
     */
    @java.lang.Override
    public boolean hasThree() {
      return three_ != null;
    }
    /**
     * <code>.MessageThree three = 2;</code>
     * @return The three.
     */
    @java.lang.Override
    public 0NestedType.MessageThree getThree() {
      return three_ == null ? 0NestedType.MessageThree.getDefaultInstance() : three_;
    }
    /**
     * <code>.MessageThree three = 2;</code>
     */
    @java.lang.Override
    public 0NestedType.MessageThreeOrBuilder getThreeOrBuilder() {
      return getThree();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (three_ != null) {
        output.writeMessage(2, getThree());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (three_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getThree());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 1Imports.MessageImport)) {
        return super.equals(obj);
      }
      1Imports.MessageImport other = (1Imports.MessageImport) obj;

      if (hasThree() != other.hasThree()) return false;
      if (hasThree()) {
        if (!getThree()
            .equals(other.getThree())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasThree()) {
        hash = (37 * hash) + THREE_FIELD_NUMBER;
        hash = (53 * hash) + getThree().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 1Imports.MessageImport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1Imports.MessageImport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1Imports.MessageImport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1Imports.MessageImport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1Imports.MessageImport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 1Imports.MessageImport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 1Imports.MessageImport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1Imports.MessageImport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1Imports.MessageImport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 1Imports.MessageImport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 1Imports.MessageImport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 1Imports.MessageImport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(1Imports.MessageImport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageImport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageImport)
        1Imports.MessageImportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 1Imports.internal_static_MessageImport_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 1Imports.internal_static_MessageImport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                1Imports.MessageImport.class, 1Imports.MessageImport.Builder.class);
      }

      // Construct using 1Imports.MessageImport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (threeBuilder_ == null) {
          three_ = null;
        } else {
          three_ = null;
          threeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 1Imports.internal_static_MessageImport_descriptor;
      }

      @java.lang.Override
      public 1Imports.MessageImport getDefaultInstanceForType() {
        return 1Imports.MessageImport.getDefaultInstance();
      }

      @java.lang.Override
      public 1Imports.MessageImport build() {
        1Imports.MessageImport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 1Imports.MessageImport buildPartial() {
        1Imports.MessageImport result = new 1Imports.MessageImport(this);
        if (threeBuilder_ == null) {
          result.three_ = three_;
        } else {
          result.three_ = threeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 1Imports.MessageImport) {
          return mergeFrom((1Imports.MessageImport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(1Imports.MessageImport other) {
        if (other == 1Imports.MessageImport.getDefaultInstance()) return this;
        if (other.hasThree()) {
          mergeThree(other.getThree());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        1Imports.MessageImport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (1Imports.MessageImport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private 0NestedType.MessageThree three_;
      private com.google.protobuf.SingleFieldBuilderV3<
          0NestedType.MessageThree, 0NestedType.MessageThree.Builder, 0NestedType.MessageThreeOrBuilder> threeBuilder_;
      /**
       * <code>.MessageThree three = 2;</code>
       * @return Whether the three field is set.
       */
      public boolean hasThree() {
        return threeBuilder_ != null || three_ != null;
      }
      /**
       * <code>.MessageThree three = 2;</code>
       * @return The three.
       */
      public 0NestedType.MessageThree getThree() {
        if (threeBuilder_ == null) {
          return three_ == null ? 0NestedType.MessageThree.getDefaultInstance() : three_;
        } else {
          return threeBuilder_.getMessage();
        }
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public Builder setThree(0NestedType.MessageThree value) {
        if (threeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          three_ = value;
          onChanged();
        } else {
          threeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public Builder setThree(
          0NestedType.MessageThree.Builder builderForValue) {
        if (threeBuilder_ == null) {
          three_ = builderForValue.build();
          onChanged();
        } else {
          threeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public Builder mergeThree(0NestedType.MessageThree value) {
        if (threeBuilder_ == null) {
          if (three_ != null) {
            three_ =
              0NestedType.MessageThree.newBuilder(three_).mergeFrom(value).buildPartial();
          } else {
            three_ = value;
          }
          onChanged();
        } else {
          threeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public Builder clearThree() {
        if (threeBuilder_ == null) {
          three_ = null;
          onChanged();
        } else {
          three_ = null;
          threeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public 0NestedType.MessageThree.Builder getThreeBuilder() {
        
        onChanged();
        return getThreeFieldBuilder().getBuilder();
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      public 0NestedType.MessageThreeOrBuilder getThreeOrBuilder() {
        if (threeBuilder_ != null) {
          return threeBuilder_.getMessageOrBuilder();
        } else {
          return three_ == null ?
              0NestedType.MessageThree.getDefaultInstance() : three_;
        }
      }
      /**
       * <code>.MessageThree three = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          0NestedType.MessageThree, 0NestedType.MessageThree.Builder, 0NestedType.MessageThreeOrBuilder> 
          getThreeFieldBuilder() {
        if (threeBuilder_ == null) {
          threeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              0NestedType.MessageThree, 0NestedType.MessageThree.Builder, 0NestedType.MessageThreeOrBuilder>(
                  getThree(),
                  getParentForChildren(),
                  isClean());
          three_ = null;
        }
        return threeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageImport)
    }

    // @@protoc_insertion_point(class_scope:MessageImport)
    private static final 1Imports.MessageImport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 1Imports.MessageImport();
    }

    public static 1Imports.MessageImport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageImport>
        PARSER = new com.google.protobuf.AbstractParser<MessageImport>() {
      @java.lang.Override
      public MessageImport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageImport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageImport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageImport> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 1Imports.MessageImport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageImport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageImport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0171.imports.proto\032\0230.nested_type.proto\"-" +
      "\n\rMessageImport\022\034\n\005three\030\002 \001(\0132\r.Message" +
      "Threeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          0NestedType.getDescriptor(),
        });
    internal_static_MessageImport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageImport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageImport_descriptor,
        new java.lang.String[] { "Three", });
    0NestedType.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
