// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 2b.use-package.proto

public final class 2BUsePackage {
  private 2BUsePackage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageUsePackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageUsePackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     * @return Whether the hello field is set.
     */
    boolean hasHello();
    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     * @return The hello.
     */
    my.package.2APackage.MessagePackage getHello();
    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     */
    my.package.2APackage.MessagePackageOrBuilder getHelloOrBuilder();
  }
  /**
   * Protobuf type {@code MessageUsePackage}
   */
  public static final class MessageUsePackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageUsePackage)
      MessageUsePackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageUsePackage.newBuilder() to construct.
    private MessageUsePackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageUsePackage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageUsePackage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageUsePackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              my.package.2APackage.MessagePackage.Builder subBuilder = null;
              if (hello_ != null) {
                subBuilder = hello_.toBuilder();
              }
              hello_ = input.readMessage(my.package.2APackage.MessagePackage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hello_);
                hello_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return 2BUsePackage.internal_static_MessageUsePackage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return 2BUsePackage.internal_static_MessageUsePackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              2BUsePackage.MessageUsePackage.class, 2BUsePackage.MessageUsePackage.Builder.class);
    }

    public static final int HELLO_FIELD_NUMBER = 1;
    private my.package.2APackage.MessagePackage hello_;
    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     * @return Whether the hello field is set.
     */
    @java.lang.Override
    public boolean hasHello() {
      return hello_ != null;
    }
    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     * @return The hello.
     */
    @java.lang.Override
    public my.package.2APackage.MessagePackage getHello() {
      return hello_ == null ? my.package.2APackage.MessagePackage.getDefaultInstance() : hello_;
    }
    /**
     * <code>.my.package.MessagePackage hello = 1;</code>
     */
    @java.lang.Override
    public my.package.2APackage.MessagePackageOrBuilder getHelloOrBuilder() {
      return getHello();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hello_ != null) {
        output.writeMessage(1, getHello());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hello_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHello());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof 2BUsePackage.MessageUsePackage)) {
        return super.equals(obj);
      }
      2BUsePackage.MessageUsePackage other = (2BUsePackage.MessageUsePackage) obj;

      if (hasHello() != other.hasHello()) return false;
      if (hasHello()) {
        if (!getHello()
            .equals(other.getHello())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHello()) {
        hash = (37 * hash) + HELLO_FIELD_NUMBER;
        hash = (53 * hash) + getHello().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static 2BUsePackage.MessageUsePackage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static 2BUsePackage.MessageUsePackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static 2BUsePackage.MessageUsePackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static 2BUsePackage.MessageUsePackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(2BUsePackage.MessageUsePackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageUsePackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageUsePackage)
        2BUsePackage.MessageUsePackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return 2BUsePackage.internal_static_MessageUsePackage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return 2BUsePackage.internal_static_MessageUsePackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                2BUsePackage.MessageUsePackage.class, 2BUsePackage.MessageUsePackage.Builder.class);
      }

      // Construct using 2BUsePackage.MessageUsePackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (helloBuilder_ == null) {
          hello_ = null;
        } else {
          hello_ = null;
          helloBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return 2BUsePackage.internal_static_MessageUsePackage_descriptor;
      }

      @java.lang.Override
      public 2BUsePackage.MessageUsePackage getDefaultInstanceForType() {
        return 2BUsePackage.MessageUsePackage.getDefaultInstance();
      }

      @java.lang.Override
      public 2BUsePackage.MessageUsePackage build() {
        2BUsePackage.MessageUsePackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public 2BUsePackage.MessageUsePackage buildPartial() {
        2BUsePackage.MessageUsePackage result = new 2BUsePackage.MessageUsePackage(this);
        if (helloBuilder_ == null) {
          result.hello_ = hello_;
        } else {
          result.hello_ = helloBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof 2BUsePackage.MessageUsePackage) {
          return mergeFrom((2BUsePackage.MessageUsePackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(2BUsePackage.MessageUsePackage other) {
        if (other == 2BUsePackage.MessageUsePackage.getDefaultInstance()) return this;
        if (other.hasHello()) {
          mergeHello(other.getHello());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        2BUsePackage.MessageUsePackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (2BUsePackage.MessageUsePackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private my.package.2APackage.MessagePackage hello_;
      private com.google.protobuf.SingleFieldBuilderV3<
          my.package.2APackage.MessagePackage, my.package.2APackage.MessagePackage.Builder, my.package.2APackage.MessagePackageOrBuilder> helloBuilder_;
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       * @return Whether the hello field is set.
       */
      public boolean hasHello() {
        return helloBuilder_ != null || hello_ != null;
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       * @return The hello.
       */
      public my.package.2APackage.MessagePackage getHello() {
        if (helloBuilder_ == null) {
          return hello_ == null ? my.package.2APackage.MessagePackage.getDefaultInstance() : hello_;
        } else {
          return helloBuilder_.getMessage();
        }
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public Builder setHello(my.package.2APackage.MessagePackage value) {
        if (helloBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hello_ = value;
          onChanged();
        } else {
          helloBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public Builder setHello(
          my.package.2APackage.MessagePackage.Builder builderForValue) {
        if (helloBuilder_ == null) {
          hello_ = builderForValue.build();
          onChanged();
        } else {
          helloBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public Builder mergeHello(my.package.2APackage.MessagePackage value) {
        if (helloBuilder_ == null) {
          if (hello_ != null) {
            hello_ =
              my.package.2APackage.MessagePackage.newBuilder(hello_).mergeFrom(value).buildPartial();
          } else {
            hello_ = value;
          }
          onChanged();
        } else {
          helloBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public Builder clearHello() {
        if (helloBuilder_ == null) {
          hello_ = null;
          onChanged();
        } else {
          hello_ = null;
          helloBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public my.package.2APackage.MessagePackage.Builder getHelloBuilder() {
        
        onChanged();
        return getHelloFieldBuilder().getBuilder();
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      public my.package.2APackage.MessagePackageOrBuilder getHelloOrBuilder() {
        if (helloBuilder_ != null) {
          return helloBuilder_.getMessageOrBuilder();
        } else {
          return hello_ == null ?
              my.package.2APackage.MessagePackage.getDefaultInstance() : hello_;
        }
      }
      /**
       * <code>.my.package.MessagePackage hello = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          my.package.2APackage.MessagePackage, my.package.2APackage.MessagePackage.Builder, my.package.2APackage.MessagePackageOrBuilder> 
          getHelloFieldBuilder() {
        if (helloBuilder_ == null) {
          helloBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              my.package.2APackage.MessagePackage, my.package.2APackage.MessagePackage.Builder, my.package.2APackage.MessagePackageOrBuilder>(
                  getHello(),
                  getParentForChildren(),
                  isClean());
          hello_ = null;
        }
        return helloBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageUsePackage)
    }

    // @@protoc_insertion_point(class_scope:MessageUsePackage)
    private static final 2BUsePackage.MessageUsePackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new 2BUsePackage.MessageUsePackage();
    }

    public static 2BUsePackage.MessageUsePackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageUsePackage>
        PARSER = new com.google.protobuf.AbstractParser<MessageUsePackage>() {
      @java.lang.Override
      public MessageUsePackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageUsePackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageUsePackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageUsePackage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public 2BUsePackage.MessageUsePackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageUsePackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageUsePackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0242b.use-package.proto\032\0202a.package.proto" +
      "\">\n\021MessageUsePackage\022)\n\005hello\030\001 \001(\0132\032.m" +
      "y.package.MessagePackageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          my.package.2APackage.getDescriptor(),
        });
    internal_static_MessageUsePackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageUsePackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageUsePackage_descriptor,
        new java.lang.String[] { "Hello", });
    my.package.2APackage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
