# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: complex.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomplex.proto\x12\x0f\x65xample.complex\"!\n\x05\x44ummy\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"f\n\x07\x43omplex\x12,\n\x0csingle_dummy\x18\x01 \x01(\x0b\x32\x16.example.complex.Dummy\x12-\n\rlist_of_dummy\x18\x02 \x03(\x0b\x32\x16.example.complex.Dummyb\x06proto3')



_DUMMY = DESCRIPTOR.message_types_by_name['Dummy']
_COMPLEX = DESCRIPTOR.message_types_by_name['Complex']
Dummy = _reflection.GeneratedProtocolMessageType('Dummy', (_message.Message,), {
  'DESCRIPTOR' : _DUMMY,
  '__module__' : 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.complex.Dummy)
  })
_sym_db.RegisterMessage(Dummy)

Complex = _reflection.GeneratedProtocolMessageType('Complex', (_message.Message,), {
  'DESCRIPTOR' : _COMPLEX,
  '__module__' : 'complex_pb2'
  # @@protoc_insertion_point(class_scope:example.complex.Complex)
  })
_sym_db.RegisterMessage(Complex)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUMMY._serialized_start=34
  _DUMMY._serialized_end=67
  _COMPLEX._serialized_start=69
  _COMPLEX._serialized_end=171
# @@protoc_insertion_point(module_scope)
