# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enumeration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65numeration.proto\x12\x13\x65xample.enumeration\"?\n\x0b\x45numeration\x12\x30\n\teye_color\x18\x01 \x01(\x0e\x32\x1d.example.enumeration.EyeColor*_\n\x08\x45yeColor\x12\x18\n\x14\x45YECOLOR_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x45YECOLOR_GREEN\x10\x01\x12\x11\n\rEYECOLOR_BLUE\x10\x02\x12\x12\n\x0e\x45YECOLOR_BROWN\x10\x03\x62\x06proto3')

_EYECOLOR = DESCRIPTOR.enum_types_by_name['EyeColor']
EyeColor = enum_type_wrapper.EnumTypeWrapper(_EYECOLOR)
EYECOLOR_UNSPECIFIED = 0
EYECOLOR_GREEN = 1
EYECOLOR_BLUE = 2
EYECOLOR_BROWN = 3


_ENUMERATION = DESCRIPTOR.message_types_by_name['Enumeration']
Enumeration = _reflection.GeneratedProtocolMessageType('Enumeration', (_message.Message,), {
  'DESCRIPTOR' : _ENUMERATION,
  '__module__' : 'enumeration_pb2'
  # @@protoc_insertion_point(class_scope:example.enumeration.Enumeration)
  })
_sym_db.RegisterMessage(Enumeration)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EYECOLOR._serialized_start=107
  _EYECOLOR._serialized_end=202
  _ENUMERATION._serialized_start=42
  _ENUMERATION._serialized_end=105
# @@protoc_insertion_point(module_scope)
