# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: maps.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmaps.proto\x12\x0c\x65xample.maps\"(\n\tSizePrice\x12\x0c\n\x04size\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x05\"\x80\x01\n\x08\x44rinkMap\x12.\n\x04menu\x18\x01 \x03(\x0b\x32 .example.maps.DrinkMap.MenuEntry\x1a\x44\n\tMenuEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.example.maps.SizePrice:\x02\x38\x01\x62\x06proto3')



_SIZEPRICE = DESCRIPTOR.message_types_by_name['SizePrice']
_DRINKMAP = DESCRIPTOR.message_types_by_name['DrinkMap']
_DRINKMAP_MENUENTRY = _DRINKMAP.nested_types_by_name['MenuEntry']
SizePrice = _reflection.GeneratedProtocolMessageType('SizePrice', (_message.Message,), {
  'DESCRIPTOR' : _SIZEPRICE,
  '__module__' : 'maps_pb2'
  # @@protoc_insertion_point(class_scope:example.maps.SizePrice)
  })
_sym_db.RegisterMessage(SizePrice)

DrinkMap = _reflection.GeneratedProtocolMessageType('DrinkMap', (_message.Message,), {

  'MenuEntry' : _reflection.GeneratedProtocolMessageType('MenuEntry', (_message.Message,), {
    'DESCRIPTOR' : _DRINKMAP_MENUENTRY,
    '__module__' : 'maps_pb2'
    # @@protoc_insertion_point(class_scope:example.maps.DrinkMap.MenuEntry)
    })
  ,
  'DESCRIPTOR' : _DRINKMAP,
  '__module__' : 'maps_pb2'
  # @@protoc_insertion_point(class_scope:example.maps.DrinkMap)
  })
_sym_db.RegisterMessage(DrinkMap)
_sym_db.RegisterMessage(DrinkMap.MenuEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DRINKMAP_MENUENTRY._options = None
  _DRINKMAP_MENUENTRY._serialized_options = b'8\001'
  _SIZEPRICE._serialized_start=28
  _SIZEPRICE._serialized_end=68
  _DRINKMAP._serialized_start=71
  _DRINKMAP._serialized_end=199
  _DRINKMAP_MENUENTRY._serialized_start=131
  _DRINKMAP_MENUENTRY._serialized_end=199
# @@protoc_insertion_point(module_scope)
