# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: oneofs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0coneofs.proto\x12\x0e\x65xample.oneofs\"2\n\x06Result\x12\x0e\n\x04this\x18\x01 \x01(\tH\x00\x12\x0e\n\x04that\x18\x02 \x01(\tH\x00\x42\x08\n\x06resultb\x06proto3')



_RESULT = DESCRIPTOR.message_types_by_name['Result']
Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'oneofs_pb2'
  # @@protoc_insertion_point(class_scope:example.oneofs.Result)
  })
_sym_db.RegisterMessage(Result)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULT._serialized_start=32
  _RESULT._serialized_end=82
# @@protoc_insertion_point(module_scope)
